-- return {
--   cmd = { "ruff", "server" },
--   root_markers = { "pyproject.toml", ".git" },
--
--   workspace_required = true,
--   init_options = {
--     settings = {
--       -- Ruff language server settings go here
--     },
--   },
-- }
